Whispers - start text under "whispered" not inline
iNPUTmice/Conversations pull request #3654
Opened 2020-03-07 09:56 UTC by anjandev

closes #3651

2020-03-07 21:00 UTC, licaon-kter commented
Wow, so simple? Thanks

2020-04-24 22:08 UTC, licaon-kter commented
Any blockers?

2020-05-27 10:30 UTC, licaon-kter commented
There's an UI refactor that blocks this?

2021-02-10 14:12 UTC, mimi89999 requested changes

2021-02-10 14:12 UTC, mimi89999 commented on src/main/res/values/strings.xml
> +    <string name="private_message">whispered\n</string>
Please don't do it like that. The trailing newline can be accidentally removed by translators. There are better ways to do that. Please see `src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java`

2021-03-18 08:32 UTC, iNPUTmice commented on src/main/res/values/strings.xml
> +    <string name="private_message">whispered\n</string>
I agree

2021-03-18 08:32 UTC, closed without merging

2021-03-18 08:40 UTC, licaon-kter commented
@mimi89999 so you're gonna PR?

2021-10-03 08:45 UTC, licaon-kter commented on src/main/res/values/strings.xml
> +    <string name="private_message">whispered\n</string>
@mimi89999 newlines and special chars are enforced by the translation portal, afaik

2021-10-03 09:02 UTC, iNPUTmice commented on src/main/res/values/strings.xml
> +    <string name="private_message">whispered\n</string>
That's still not a good solution. The proper solution is to work with an additional TextView.